/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125pagesAboutRouteImport } from './routes/{-$locale}/(pages)/about'
import { Route as Char123LocaleChar125pagesBlogIndexRouteImport } from './routes/{-$locale}/(pages)/blog/index'
import { Route as Char123LocaleChar125pagesBlogSlugRouteImport } from './routes/{-$locale}/(pages)/blog/$slug'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125pagesAboutRoute =
  Char123LocaleChar125pagesAboutRouteImport.update({
    id: '/(pages)/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125pagesBlogIndexRoute =
  Char123LocaleChar125pagesBlogIndexRouteImport.update({
    id: '/(pages)/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125pagesBlogSlugRoute =
  Char123LocaleChar125pagesBlogSlugRouteImport.update({
    id: '/(pages)/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/about': typeof Char123LocaleChar125pagesAboutRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125pagesBlogSlugRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125pagesBlogIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/about': typeof Char123LocaleChar125pagesAboutRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125pagesBlogSlugRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125pagesBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/(pages)/about': typeof Char123LocaleChar125pagesAboutRoute
  '/{-$locale}/(pages)/blog/$slug': typeof Char123LocaleChar125pagesBlogSlugRoute
  '/{-$locale}/(pages)/blog/': typeof Char123LocaleChar125pagesBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/about'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/(pages)/about'
    | '/{-$locale}/(pages)/blog/$slug'
    | '/{-$locale}/(pages)/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(pages)/about': {
      id: '/{-$locale}/(pages)/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125pagesAboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(pages)/blog/': {
      id: '/{-$locale}/(pages)/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125pagesBlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(pages)/blog/$slug': {
      id: '/{-$locale}/(pages)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125pagesBlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125pagesAboutRoute: typeof Char123LocaleChar125pagesAboutRoute
  Char123LocaleChar125pagesBlogSlugRoute: typeof Char123LocaleChar125pagesBlogSlugRoute
  Char123LocaleChar125pagesBlogIndexRoute: typeof Char123LocaleChar125pagesBlogIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125pagesAboutRoute: Char123LocaleChar125pagesAboutRoute,
    Char123LocaleChar125pagesBlogSlugRoute:
      Char123LocaleChar125pagesBlogSlugRoute,
    Char123LocaleChar125pagesBlogIndexRoute:
      Char123LocaleChar125pagesBlogIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
